server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    # React SPA: unknown routes bhi index.html serve karein
    location / {
        try_files $uri /index.html;
    }

    # /api calls ko backend container tak forward karo
    location /api/ {
        proxy_pass http://backend:8000/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}